name: Deploy to OpenCPU public cloud

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notify OpenCPU
        run: |
          Rscript -e 'devtools::install()'
          curl -X POST https://cloud.opencpu.org/ocpu/github/WintonCentre/predictv30r
